/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ListingID]
      ,[pedestrian_friendly]
      ,[transit_friendly]
      ,[car_friendly]
      ,[groceries]
      ,[primary_schools]
      ,[high_schools]
      ,[daycares]
      ,[parks]
      ,[restaurants]
      ,[cafes]
      ,[shopping]
      ,[nightlife]
      ,[quiet]
      ,[vibrant]
  FROM [Hackathon].[dbo].[LISTINGS_LOCATION_SCORES]
